# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

# website title
title = "azuar4e"
# Hostname (and path) to the root
baseURL = "https://azuar4e.github.io/"
# theme list
theme = ["FixIt"]
defaultContentLanguage = "en"
# languageCode = "en"
# languageName = "English"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false
[pagination]
  pagerSize = 12
copyright = ""
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true
# the main sections of a site
mainSections = []

[languages]

  [languages.en]
    languageName = "English"
    languageCode = "en"
    contentDir = "content/en"
    weight = 1
    hasCJKLanguage = false
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

  [languages.es]
    languageName = "Español"
    languageCode = "es"
    contentDir = "content/es"
    weight = 2
    hasCJKLanguage = false
    copyright = "Este trabajo está bajo una licencia Creative Commons Atribución-NoComercial 4.0 Internacional."

# # -------------------------------------------------------------------------------------
# # Hugo Configuration
# # See: https://gohugo.io/getting-started/configuration/
# # -------------------------------------------------------------------------------------

# # website title
# title = "azuar4e"
# # Hostname (and path) to the root
# baseURL = "https://azuar4e.github.io/"
# # theme list
# theme = ["FixIt"]
# defaultContentLanguage = "en"
# hasCJKLanguage = false
# timeZone = "Europe/Madrid"
# newContentEditor = "code"
# enableEmoji = true
# enableGitInfo = true
# enableRobotsTXT = true

# buildDrafts = false
# summaryLength = 150
# titleCaseStyle = "ap"
# capitalizeListTitles = false

# ignoreLogs = [
#   "error-get-remote-image",
#   "error-get-remote-json",
#   "error-get-gh-repo",
#   "error-remote-getjson",
#   "error-missing-instagram-accesstoken",
#   "warning-dev-version"
# ]