languageName = "Español"
languageCode = "es"
contentDir = "content/es"
weight = 2

[[menu.main]]
identifier = "archives"
name = "Archivos"
url = "/archives/"
weight = 1
[menu.main.params]
icon = "fa-solid fa-archive"

[[menu.main]]
identifier = "categories"
name = "Categorías"
url = "/categories/"
weight = 2
[menu.main.params]
icon = "fa-solid fa-folder-tree"

[[menu.main]]
identifier = "about"
name = "Acerca de"
url = "/about/"
weight = 100
[menu.main.params]
icon = "fa-solid fa-quote-left"

[[menu.main]]
identifier = "tags"
name = "Etiquetas"
url = "/tags/"
weight = 3
[menu.main.params]
icon = "fa-solid fa-tags"

[params.search]
  enable = true
  type = "algolia"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 50
  highlightTag = "em"
  absoluteURL = false

  [params.search.algolia]
    index = "miblog_algolia_pages_es"
    appID = "L5YIFQ7E5O"
    searchKey = "4730818b3e23ce341fdbb2edbce34eda"
