# -------------------------------------------------------------------------------------
# Markup related configuration in Hugo
# See: https://gohugo.io/getting-started/configuration-markup/
# -------------------------------------------------------------------------------------

  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[highlight]
########## necessary configurations ##########
# https://github.com/hugo-fixit/FixIt/issues/43
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false
########## necessary configurations ##########
guessSyntax = true
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # https://gohugo.io/getting-started/configuration-markup/#goldmark
[goldmark]
# duplicateResourceFiles = false
    [goldmark.extensions]
        definitionList = true
        footnote = true
        linkify = true
        # linkifyProtocol = 'https'
        strikethrough = false
        table = true
        taskList = true
        typographer = true
        # https://gohugo.io/getting-started/configuration-markup/#extras
        [goldmark.extensions.extras]
        [goldmark.extensions.extras.delete]
            enable = true
        [goldmark.extensions.extras.insert]
            enable = true
        [goldmark.extensions.extras.mark]
            enable = true
        [goldmark.extensions.extras.subscript]
            enable = true
        [goldmark.extensions.extras.superscript]
            enable = true
    # TODO passthrough refactor https://gohugo.io/render-hooks/passthrough/
    # TODO hugo 0.122.0 https://gohugo.io/content-management/mathematics/
    # [goldmark.extensions.passthrough]
    #   enable = true
    #   [goldmark.extensions.passthrough.delimiters]
    #     block = [['\[', '\]'], ['$$', '$$']]
    #     inline = [['\(', '\)'], ['$', '$']]
    [goldmark.parser]
        autoHeadingID = true
        autoHeadingIDType = "github"
        wrapStandAloneImageWithinParagraph = true
        [goldmark.parser.attribute]
        block = true
        title = true
    [goldmark.renderer]
        hardWraps = false
        # whether to use HTML tags directly in the document
        unsafe = true
        xhtml = false